### ISSUE TITLE
Missing files in unit tests

### ISSUE THREAD

**Issue by vojtaBelovsky** [jonasschaude/NewsApp-With-CleanArchitecture#1]
Hi Jonas,

firstly thanks for great medium article and project example.

I've downloaded project and was curious about unit tests, but I can't run it, because there are files that are missing - check the screenshot.

<img width="357" alt="Screenshot 2023-07-20 at 11 51 11" src="https://github.com/jonasschaude/NewsApp-With-CleanArchitecture/assets/3873468/ffd4d2d8-6302-4ef8-8a38-51eaee65cd3e">

Can you add those missing files please?

Thanks,

Vojta

**Comment by jonasschaude** [comment]
Hey Vojta,

thanks a lot for your feedback and letting me know that there are issues in the demo project. I am glad to hear that you like the medium article.

I added the missing files that you should now be able to compile the project and also execute the unittests without any issues. I will close the issue for now.

If you have further questions, please let me know.

Cheers
Jonas
